languageCode = "en-us"
title = "Talkspace"
baseurl = "http://talkspace.club/"
theme = "aerial"

[params]
  name = "Talkspace"
  about = "Coming soon"
  copyright = "Ron Forbes"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.png"